Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Models/ErrorViewModel.cs
using System;

namespace AutoLotMVC_Core2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoLotMVC_Core2.Models;

namespace AutoLotMVC_Core2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Controllers/InventoryController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AutoLotDAL_Core2.Models;
using AutoLotDAL_Core2.Repos;

namespace AutoLotMVC_Core2.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IInventoryRepo _repo;

        public InventoryController(IInventoryRepo repo)
        {
            _repo = repo;
        }

        // GET: Inventory
        public IActionResult Index()
        {
            //return View(_repo.GetAll());
            return View("IndexWithViewComponent");
        }

        // GET: Inventory/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Inventory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Make,Color,PetName")] Inventory inventory)
        {
            if (!ModelState.IsValid) return View(inventory);
            try
            {
                _repo.Add(inventory);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                return View(inventory);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Inventory/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }
            return View(inventory);
        }

        // POST: Inventory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Make,Color,PetName,Id,Timestamp")] Inventory inventory)
        {
            if (id != inventory.Id)
            {
                return BadRequest();
            }
            if (!ModelState.IsValid) return View(inventory);
            try
            {
                _repo.Update(inventory);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to save the record. Another user has updated it. {ex.Message}");
                return View(inventory);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                return View(inventory);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Inventory/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventory/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] Inventory inventory)
        {
            try
            {
                _repo.Delete(inventory);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/ViewComponents/InventoryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoLotDAL_Core2.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace AutoLotMVC_Core2.ViewComponents
{
    public class InventoryViewComponent : ViewComponent
    {
        private readonly IInventoryRepo _repo;

        public InventoryViewComponent(IInventoryRepo repo)
        {
            _repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cars = _repo.GetAll(x => x.Make, true);
            if (cars != null)
            {
                return View("InventoryPartialView", cars);
            }
            return new ContentViewComponentResult("Unable to locate records.");
        }
    }
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/Create.cshtml
@model AutoLotDAL_Core2.Models.Inventory

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @Html.EditorForModel()

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/Delete.cshtml
@model AutoLotDAL_Core2.Models.Inventory

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Timestamp" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/Details.cshtml
@model AutoLotDAL_Core2.Models.Inventory

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/Edit.cshtml
@model AutoLotDAL_Core2.Models.Inventory

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="Timestamp"/>
            @Html.EditorForModel()
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/EditorTemplates/Inventory.cshtml
@using AutoLotDAL_Core2.Models
@model AutoLotDAL_Core2.Models.Inventory
<h4>Inventory</h4>
<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Make" class="control-label"></label>
    <input asp-for="Make" class="form-control"/>
    <span asp-validation-for="Make" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Color" class="control-label"></label>
    <input asp-for="Color" class="form-control"/>
    <span asp-validation-for="Color" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="PetName" class="control-label"></label>
    <input asp-for="PetName" class="form-control"/>
    <span asp-validation-for="PetName" class="text-danger"></span>
</div>

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/Index.cshtml
@using AutoLotDAL_Core2.Models
@model IEnumerable<Inventory>
@functions
{
    public IList<Inventory> SortCars(IList<Inventory> cars)
    {
        var list = from s in cars orderby s.PetName select s;
        return list.ToList();
    }
}
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Make)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Color)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PetName)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in SortCars(Model.ToList()))
    {
        @Html.DisplayFor(modelItem => item, "InventoryList")
    }
    </tbody>
</table>

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Inventory/IndexWithViewComponent.cshtml
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
    <vc:Inventory></vc:Inventory>

Chapter_33/AutoLotMVC_Core2/AutoLotMVC_Core2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoLotMVC_Core2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AutoLotMVC_Core2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - AutoLotMVC_Core2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>